import { Inter } from 'next/font/google'
import './globals.css'
import "./globals.css";
import "../styles/variables.scss";
import "../styles/general.scss";
import "../styles/pages.scss";
import "../styles/components.scss";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mainLayout">
          {/* <SideBar /> */}
          <div className="mainPage">
            {/* <NavBar /> */}
            {children}
            {/* <Footer /> */}
          </div>
        </div>
      </body>
    </html>
  )
}
